{{- $fullName := include "capi-vcluster.fullname" . -}}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{ $fullName }}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: null
      repo: null
      version: null
    values: |
      service:
        type: LoadBalancer
  kubernetesVersion: 1.27.4
